<?php
/**
 * Prime Cache uninstall.
 *
 * Runs when the plugin is deleted via WordPress admin.
 */

defined( 'WP_UNINSTALL_PLUGIN' ) || exit;

// This uninstall script removes Prime Cache's own cache files and directories
// directly (a one-shot cleanup, not the hot path), and uses a few "$pc_"-prefixed
// procedural globals. WP_Filesystem is not used here, and the prefix avoids
// collisions, so the direct-file and prefix sniffs are disabled for this file.
// phpcs:disable WordPress.WP.AlternativeFunctions, WordPress.NamingConventions.PrefixAllGlobals

// Remove plugin option.
delete_option( 'prime_cache_settings' );

// Remove .htaccess rules. insert_with_markers() lives in wp-admin/includes/misc.php
// which the uninstall bootstrap does not auto-load — pull it in explicitly so the
// Prime Cache marker block does not get left behind.
$htaccess = ABSPATH . '.htaccess';
if ( file_exists( $htaccess ) ) {
	if ( ! function_exists( 'insert_with_markers' ) ) {
		$pc_misc = ABSPATH . 'wp-admin/includes/misc.php';
		if ( is_readable( $pc_misc ) ) {
			require_once $pc_misc;
		}
	}
	if ( function_exists( 'insert_with_markers' ) ) {
		insert_with_markers( $htaccess, 'Prime Cache', array() );
	}
}

// Remove advanced-cache.php if ours. Match all signature variants the
// install path recognizes — Prime_Cache_Config::get_advanced_cache_owner()
// treats `PRIME_CACHE_ADVANCED_CACHE` and `Generated by Prime Cache` as
// legacy ours-markers, and an upgrade-then-uninstall on a read-only
// drop-in environment can leave one of those formats in place. Without
// matching them here, the file would persist after uninstall and
// WordPress would keep loading a dead drop-in on every request.
$dropin = WP_CONTENT_DIR . '/advanced-cache.php';
if ( file_exists( $dropin ) ) {
	$content = file_get_contents( $dropin ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	if ( is_string( $content )
		&& ( false !== strpos( $content, 'PRIME_CACHE_DROPIN_SIGNATURE' )
			|| false !== strpos( $content, 'PRIME_CACHE_ADVANCED_CACHE' )
			|| false !== strpos( $content, 'Generated by Prime Cache' ) ) ) {
		@unlink( $dropin );
	}
}

// Remove object-cache.php if ours.
$object_dropin = WP_CONTENT_DIR . '/object-cache.php';
if ( file_exists( $object_dropin ) ) {
	$content = file_get_contents( $object_dropin ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	if ( is_string( $content ) && false !== strpos( $content, 'PRIME_CACHE_DROPIN_SIGNATURE' ) ) {
		@unlink( $object_dropin );
	}
}

// Remove WP_CACHE from wp-config.php — only the line Prime Cache added.
$config_paths = array(
	ABSPATH . 'wp-config.php',
	dirname( ABSPATH ) . '/wp-config.php',
);

foreach ( $config_paths as $config_path ) {
	if ( file_exists( $config_path ) && is_writable( $config_path ) ) {
		$config_content = file_get_contents( $config_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( ! is_string( $config_content ) || false === strpos( $config_content, 'Added by Prime Cache' ) ) {
			continue; // Unreadable or no Prime Cache line — check next candidate.
		}
		$config_content = preg_replace(
			'#^\s*define\s*\(\s*[\'"]WP_CACHE[\'"]\s*,\s*[^)]+\)\s*;\s*//\s*Added by Prime Cache[^\n]*\n?#mi',
			'',
			$config_content
		);
		if ( null === $config_content ) {
			break; // PCRE error — leave wp-config.php untouched.
		}
		$config_content = preg_replace( "#\n{3,}#", "\n\n", $config_content );
		// Atomic write: temp file + rename.
		$tempfile = $config_path . '.tmp.' . getmypid();
		if ( null !== $config_content && false !== file_put_contents( $tempfile, $config_content ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
			if ( ! rename( $tempfile, $config_path ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename
				@unlink( $tempfile );
			}
		}
		break; // Found and cleaned — done.
	}
}

// Helper: recursively remove a directory tree.
$pc_uninstall_rmtree = function ( $dir ) {
	if ( ! is_dir( $dir ) ) {
		return;
	}
	// Safety: only ever recurse-delete inside Prime Cache's own cache roots, so a
	// miscomputed or symlinked $dir can never escalate into deleting unrelated
	// files elsewhere under wp-content.
	$real   = realpath( $dir );
	$within = false;
	if ( false !== $real ) {
		foreach ( array( WP_CONTENT_DIR . '/cache/prime-cache', WP_CONTENT_DIR . '/cache/prime-cache-fo' ) as $allowed ) {
			$root = realpath( $allowed );
			if ( $root && 0 === strpos( rtrim( $real, DIRECTORY_SEPARATOR ) . DIRECTORY_SEPARATOR, rtrim( $root, DIRECTORY_SEPARATOR ) . DIRECTORY_SEPARATOR ) ) {
				$within = true;
				break;
			}
		}
	}
	if ( ! $within ) {
		return;
	}
	$iter = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $dir, RecursiveDirectoryIterator::SKIP_DOTS ),
		RecursiveIteratorIterator::CHILD_FIRST
	);
	foreach ( $iter as $item ) {
		$item->isDir() ? @rmdir( $item->getPathname() ) : @unlink( $item->getPathname() );
	}
	@rmdir( $dir );
};

// Helper: rmdir only when directory is empty (preserves other installs' data
// in shared wp-content setups).
$pc_uninstall_rmdir_if_empty = function ( $dir ) {
	if ( ! is_dir( $dir ) ) {
		return;
	}
	$entries = @scandir( $dir );
	if ( false === $entries ) {
		return;
	}
	$entries = array_diff( $entries, array( '.', '..' ) );
	if ( empty( $entries ) ) {
		@rmdir( $dir );
	}
};

// Resolve the hosts this install owns. In shared wp-content setups, only these
// per-host cache buckets belong to us — nuking the whole /cache/prime-cache/
// would destroy other sites' caches.
//
// Use the same normalization as the dropin so IDN/IPv6/port-bearing hosts map to
// the same bucket name we wrote at runtime.
$pc_keyfn = __DIR__ . '/includes/cache-key-functions.php';
if ( is_readable( $pc_keyfn ) ) {
	require_once $pc_keyfn;
}
$pc_uninstall_hosts = array();
if ( function_exists( 'home_url' ) ) {
	$pc_raw_hosts = array();
	foreach ( array( home_url(), site_url() ) as $u ) {
		$h = wp_parse_url( $u, PHP_URL_HOST );
		if ( $h ) {
			$pc_raw_hosts[] = $h;
		}
	}
	// Sites that add www↔apex or alias domains via the `prime_cache_allowed_hosts`
	// filter get cache buckets for those hosts too. `prime_cache_host_history`
	// only records a host after an env change, so a site that has used an alias
	// since install never appears there — fold the filter result in directly so
	// those buckets are not orphaned. The filter is still live here: WordPress
	// loads mu-plugins, other active plugins, and the theme before uninstall.php.
	if ( function_exists( 'apply_filters' ) ) {
		/** This filter is documented in includes/class-config.php */
		$pc_raw_hosts = apply_filters( 'prime_cache_allowed_hosts', $pc_raw_hosts );
		if ( ! is_array( $pc_raw_hosts ) ) {
			$pc_raw_hosts = array();
		}
	}
	foreach ( $pc_raw_hosts as $h ) {
		if ( ! is_string( $h ) || '' === $h ) {
			continue;
		}
		$pc_uninstall_hosts[] = function_exists( '_prime_cache_normalize_host' )
			? _prime_cache_normalize_host( $h )
			: strtolower( trim( $h ) );
	}
}
// Also clean any host this install previously cached for (domain moves,
// www↔apex flips, scheme changes). Tracked in `prime_cache_host_history`
// by regenerate_env_dependent_files(). Without this, the old host's
// `wp-content/cache/prime-cache/<old>/` directory stays behind on
// uninstall even though it belongs to this install.
$pc_history = (array) get_option( 'prime_cache_host_history', array() );
foreach ( $pc_history as $past_host ) {
	if ( is_string( $past_host ) && '' !== $past_host ) {
		$pc_uninstall_hosts[] = $past_host;
	}
}
$pc_uninstall_hosts = array_unique( array_filter( $pc_uninstall_hosts ) );

// Remove only this install's cache entries under the shared cache directory.
// In shared wp-content setups a single host bucket (cache/prime-cache/<host>/)
// can hold caches for multiple subdirectory installs (example.com/site-a/,
// example.com/site-b/). Scope the purge to this install's base path so
// uninstalling one site does not wipe a sibling install's cache. Root installs
// ("/") still clear the whole host bucket — there is no path segment to
// distinguish them by.
$cache_dir    = WP_CONTENT_DIR . '/cache/prime-cache/';
$pc_base_path = '/';
if ( function_exists( 'home_url' ) ) {
	$pc_home_path = wp_parse_url( home_url( '/' ), PHP_URL_PATH );
	if ( is_string( $pc_home_path ) && '' !== $pc_home_path
		&& function_exists( '_prime_cache_normalize_path' ) ) {
		$pc_base_path = _prime_cache_normalize_path( $pc_home_path );
	}
}
foreach ( $pc_uninstall_hosts as $host ) {
	if ( '/' === $pc_base_path ) {
		$pc_uninstall_rmtree( $cache_dir . $host . '/' );
	} else {
		$pc_uninstall_rmtree( $cache_dir . $host . $pc_base_path );
		// Host bucket may now be empty if no sibling install left files behind.
		$pc_uninstall_rmdir_if_empty( $cache_dir . $host . '/' );
	}
}
// Note: stats.json at the cache root is shared with any other Prime Cache install
// pointing at the same wp-content. Leave it alone — zeroing other installs'
// counters on our uninstall would be unfriendly and the file is regenerated.
// Drop the parent dir only if no other install left files behind.
$pc_uninstall_rmdir_if_empty( $cache_dir );

// Remove only this install's config file (site-config-{install_key}.php).
global $table_prefix;
$pc_install_seed = ABSPATH . '|' . ( defined( 'DB_NAME' ) ? DB_NAME : '' )
	. '|' . ( isset( $table_prefix ) ? (string) $table_prefix : '' );
$pc_install_key  = substr( md5( $pc_install_seed ), 0, 8 );
$config_dir      = WP_CONTENT_DIR . '/prime-cache-config/';
@unlink( $config_dir . 'site-config-' . $pc_install_key . '.php' );

// Pre-upgrade builds keyed the filename off AUTH_SALT. If a rotate-then-
// uninstall path orphaned that file, remove it here too rather than leaving
// it in `prime-cache-config`.
$pc_legacy_seed = ABSPATH . '|' . ( defined( 'DB_NAME' ) ? DB_NAME : '' )
	. '|' . ( defined( 'AUTH_SALT' ) ? AUTH_SALT : '' );
$pc_legacy_key  = substr( md5( $pc_legacy_seed ), 0, 8 );
if ( $pc_legacy_key !== $pc_install_key ) {
	@unlink( $config_dir . 'site-config-' . $pc_legacy_key . '.php' );
}
// Remove the per-config-dir flock file too — write_config_file() leaves
// `.prime-cache-config.lock` behind on every settings save, which would
// otherwise keep the rmdir-if-empty check below from succeeding.
@unlink( $config_dir . '.prime-cache-config.lock' );
$pc_uninstall_rmdir_if_empty( $config_dir );

// File optimizer cache: contents are content-hashed and may be shared with other
// installs running Prime Cache against the same wp-content. Detect "last install
// standing" by checking whether any peer config files remain under
// `prime-cache-config/` after our own was removed above. If none remain, no
// other install is using prime-cache-fo and we can recursively wipe it.
// Otherwise keep the directory intact so the other installs' optimized assets
// keep serving.
$pc_other_configs_remain = false;
if ( is_dir( $config_dir ) ) {
	$peer_iter = @scandir( $config_dir );
	if ( is_array( $peer_iter ) ) {
		foreach ( $peer_iter as $entry ) {
			if ( '.' === $entry || '..' === $entry ) {
				continue;
			}
			// Only `site-config-*.php` files indicate live peers. Other
			// detritus (lockfile, stale temp) doesn't count.
			if ( 0 === strpos( $entry, 'site-config-' ) && '.php' === substr( $entry, -4 ) ) {
				$pc_other_configs_remain = true;
				break;
			}
		}
	}
}
$pc_fo_dir = WP_CONTENT_DIR . '/cache/prime-cache-fo/';
if ( $pc_other_configs_remain ) {
	$pc_uninstall_rmdir_if_empty( $pc_fo_dir );
} else {
	$pc_uninstall_rmtree( $pc_fo_dir );
}

// Remove flock sentinels created by install_advanced_cache and htaccess writers.
// These live at the WP_CONTENT_DIR root and are harmless if left behind, but
// we own them so clean them up for tidiness.
@unlink( WP_CONTENT_DIR . '/.prime-cache-acache.lock' );
@unlink( WP_CONTENT_DIR . '/.prime-cache-htaccess.lock' );

// Remove stats, preload queue, and image optimization metadata.
delete_option( 'prime_cache_stats' );
delete_option( 'prime_cache_cf_purge_queue' );
delete_option( 'prime_cache_cf_purge_retries' );
delete_option( 'prime_cache_preload_queue' );
delete_option( 'prime_cache_preload_attempts' );
delete_option( 'prime_cache_preload_lock' );
delete_option( 'prime_cache_env_snapshot' );
delete_option( 'prime_cache_host_history' );
delete_option( 'prime_cache_flush_rewrite' );
delete_option( 'prime_cache_img_stats' );
global $wpdb;
$wpdb->delete( $wpdb->postmeta, array( 'meta_key' => '_prime_cache_img_opt' ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.SlowDBQuery.slow_db_query_meta_key -- Uninstall cleanup; runs once on deletion, not cacheable.
$wpdb->delete( $wpdb->postmeta, array( 'meta_key' => '_prime_cache_disabled' ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.SlowDBQuery.slow_db_query_meta_key -- Uninstall cleanup; runs once on deletion, not cacheable.

// Remove scheduled cron events (#19).
wp_clear_scheduled_hook( 'prime_cache_cleanup_expired' );
wp_clear_scheduled_hook( 'prime_cache_preload_batch' );
wp_clear_scheduled_hook( 'prime_cache_db_cleanup' );
wp_clear_scheduled_hook( 'prime_cache_refresh_local_analytics' );
wp_clear_scheduled_hook( 'prime_cache_refresh_google_fonts' );
wp_clear_scheduled_hook( 'prime_cache_cf_deferred_purge' );
wp_clear_scheduled_hook( 'prime_cache_cf_retry_full_purge' );
delete_option( 'prime_cache_cf_full_purge_retries' );
delete_option( 'prime_cache_cf_purge_failed' );
wp_clear_scheduled_hook( 'prime_cache_cleanup_gf_options' );
// Clean up any remaining Google Fonts pending options.
$wpdb->query( "DELETE FROM {$wpdb->options} WHERE option_name LIKE 'prime\_cache\_gf\_%'" ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Uninstall cleanup of leftover options; runs once on deletion, not cacheable.

// Remove transients (#20). Includes the font-preload cache (prime_cache_font_cache)
// and any legacy per-set font transients (prime_cache_preload_fonts*).
$wpdb->query( "DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_prime\_cache\_imgdim\_%' OR option_name LIKE '_transient_timeout_prime\_cache\_imgdim\_%' OR option_name LIKE '_transient_pc_imgdim_%' OR option_name LIKE '_transient_timeout_pc_imgdim_%' OR option_name LIKE '_transient_prime\_cache\_font\_cache' OR option_name LIKE '_transient_timeout_prime\_cache\_font\_cache' OR option_name LIKE '_transient_prime\_cache\_preload\_fonts%' OR option_name LIKE '_transient_timeout_prime\_cache\_preload\_fonts%'" ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Uninstall cleanup of leftover transients; runs once on deletion, not cacheable. Covers the current prime_cache_imgdim_ prefix and the pre-1.10.24 pc_imgdim_ key.
