<?php
/**
 * Nginx configuration snippet generator.
 *
 * Nginx has no .htaccess equivalent, so Prime Cache cannot install its
 * PHP-less fast path automatically there. This class generates a copy-paste
 * server-block snippet that serves cache files directly from disk — the
 * nginx counterpart of Prime_Cache_Htaccess::build_rewrite_rules(), kept
 * deliberately condition-for-condition in sync with it so both fast paths
 * bypass PHP for exactly the same requests.
 *
 * @package Prime_Cache
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Prime_Cache_Nginx {

	/**
	 * Whether the current server looks like nginx.
	 */
	public static function is_nginx() {
		$software = isset( $_SERVER['SERVER_SOFTWARE'] ) ? sanitize_text_field( wp_unslash( $_SERVER['SERVER_SOFTWARE'] ) ) : '';
		return false !== stripos( $software, 'nginx' );
	}

	/**
	 * Build the copy-paste nginx snippet for the given settings.
	 *
	 * @param array $settings Plugin settings.
	 * @return string Snippet text ('' when page caching is disabled).
	 */
	public static function build_snippet( $settings ) {
		if ( empty( $settings['cache_enabled'] ) ) {
			return '';
		}

		$cache_path = 'wp-content/cache/prime-cache';
		if ( defined( 'PRIME_CACHE_CACHE_DIR' ) && defined( 'ABSPATH' ) ) {
			$rel = str_replace( untrailingslashit( ABSPATH ), '', untrailingslashit( PRIME_CACHE_CACHE_DIR ) );
			if ( $rel && '/' !== $rel[0] ) {
				$rel = '/' . $rel;
			}
			if ( $rel && false === strpos( $rel, '..' ) ) {
				$cache_path = ltrim( $rel, '/' );
			}
		}

		$sep_mobile = ! empty( $settings['cache_mobile'] ) && ! empty( $settings['cache_mobile_separate'] );
		$use_gzip   = ! empty( $settings['gzip_compression'] );

		$r   = array();
		$r[] = '# ===== Prime Cache: serve cached pages without PHP (nginx) =====';
		$r[] = '# Paste inside the server { } block of this site, BEFORE the';
		$r[] = '# existing "location / { ... }". Then replace that location block';
		$r[] = '# as shown at the bottom, test with `nginx -t` and reload nginx.';
		$r[] = '# Generated by Prime Cache — regenerate after changing settings.';
		$r[] = '';
		$r[] = 'set $pc_file "/prime-cache-miss";';
		$r[] = 'set $pc_ok 1;';
		$r[] = 'set $pc_ssl "";';
		$r[] = 'set $pc_mobile "";';
		$r[] = '';
		$r[] = '# Serve cached files only for plain anonymous GETs.';
		$r[] = 'if ($request_method != GET) { set $pc_ok 0; }';
		$r[] = 'if ($args != "") { set $pc_ok 0; }';
		$r[] = 'if ($http_authorization != "") { set $pc_ok 0; }';
		$r[] = '';
		$r[] = '# ASCII-safe paths only (encoded URLs use hashed cache names the';
		$r[] = '# rewrite layer cannot reproduce — they fall through to PHP).';
		$r[] = 'if ($request_uri !~ "^[a-zA-Z0-9/_\-\.]+$") { set $pc_ok 0; }';
		$r[] = 'if ($request_uri ~ "\.\.") { set $pc_ok 0; }';
		$r[] = '';
		$r[] = '# Never fast-path WordPress system URLs.';
		$r[] = 'if ($request_uri ~* "(^|/)wp-(admin(/|$)|login\.php|cron\.php)") { set $pc_ok 0; }';
		$r[] = 'if ($request_uri ~* "(^|/)xmlrpc\.php") { set $pc_ok 0; }';
		$r[] = '';

		if ( empty( $settings['cache_logged_in'] ) ) {
			$r[] = '# Logged-in users bypass the cache.';
			$r[] = 'if ($http_cookie ~* "wordpress_logged_in_") { set $pc_ok 0; }';
		}
		$r[] = '# Commenters / password-protected posts always bypass.';
		$r[] = 'if ($http_cookie ~* "comment_author_|wp-postpass_") { set $pc_ok 0; }';
		$r[] = '';

		$r[] = '# Scheme variant. Behind a TLS-terminating proxy $scheme is http';
		$r[] = '# here — those requests safely fall through to PHP.';
		$r[] = 'if ($scheme = https) { set $pc_ssl "-https"; }';
		$r[] = '';

		if ( empty( $settings['cache_mobile'] ) ) {
			$r[] = '# Mobile cache disabled — mobile UAs go to PHP.';
			$r[] = 'if ($http_user_agent ~* "Mobile|Android|Silk/|Kindle|BlackBerry|Opera Mini|Opera Mobi|webOS") { set $pc_ok 0; }';
			$r[] = '';
		} elseif ( $sep_mobile ) {
			$r[] = '# Separate mobile cache variant.';
			$r[] = 'if ($http_user_agent ~* "Mobile|Android|Silk/|Kindle|BlackBerry|Opera Mini|Opera Mobi|webOS") { set $pc_mobile "-mobile"; }';
			$r[] = '';
		}

		$r[] = 'if ($pc_ok = 1) {';
		$r[] = '    set $pc_file "/' . $cache_path . '/${host}${request_uri}index${pc_ssl}${pc_mobile}.html";';
		$r[] = '}';
		$r[] = '';
		$r[] = '# Replace the existing "location / { ... }" with:';
		$r[] = 'location / {';
		if ( $use_gzip ) {
			$r[] = '    # Serves the pre-compressed index*.html.gz variant when present.';
			$r[] = '    gzip_static on;';
		}
		$r[] = '    try_files $pc_file $uri $uri/ /index.php?$args;';
		$r[] = '}';
		$r[] = '# ===== End Prime Cache =====';

		return implode( "\n", $r );
	}
}
