<?php
/**
 * Per-post cache control metabox.
 *
 * Adds a metabox to the post editor allowing cache to be disabled per post/page.
 */

defined( 'ABSPATH' ) || exit;

class Prime_Cache_Post_Metabox {

	const META_KEY = '_prime_cache_disabled';

	public function __construct() {
		add_action( 'add_meta_boxes', array( $this, 'add_metabox' ) );
		add_action( 'save_post', array( $this, 'save_metabox' ), 10, 2 );
	}

	/**
	 * Register the metabox for all public post types.
	 */
	public function add_metabox() {
		$post_types = get_post_types( array( 'public' => true ), 'names' );
		foreach ( $post_types as $pt ) {
			add_meta_box(
				'prime-cache-settings',
				'Prime Cache',
				array( $this, 'render' ),
				$pt,
				'side',
				'low'
			);
		}
	}

	/**
	 * Render the metabox content.
	 */
	public function render( $post ) {
		$disabled = (bool) get_post_meta( $post->ID, self::META_KEY, true );
		wp_nonce_field( 'prime_cache_metabox', 'prime_cache_metabox_nonce' );
		?>
		<label style="display:flex;align-items:center;gap:6px;cursor:pointer">
			<input type="checkbox" name="prime_cache_disabled" value="1" <?php checked( $disabled ); ?>>
			<span><?php esc_html_e( 'Disable cache for this page', 'prime-cache' ); ?></span>
		</label>
		<p class="description" style="margin-top:6px"><?php esc_html_e( 'When checked, this page will always be dynamically generated by WordPress and never served from cache.', 'prime-cache' ); ?></p>
		<?php
	}

	/**
	 * Save the metabox value.
	 */
	public function save_metabox( $post_id, $post ) {
		if ( ! isset( $_POST['prime_cache_metabox_nonce'] ) ) {
			return;
		}
		if ( ! wp_verify_nonce( $_POST['prime_cache_metabox_nonce'], 'prime_cache_metabox' ) ) {
			return;
		}
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return;
		}
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}

		$disabled = ! empty( $_POST['prime_cache_disabled'] );

		if ( $disabled ) {
			update_post_meta( $post_id, self::META_KEY, '1' );
		} else {
			delete_post_meta( $post_id, self::META_KEY );
		}
	}

	/**
	 * Check if cache is disabled for a given post.
	 *
	 * @param int $post_id Post ID.
	 * @return bool
	 */
	public static function is_cache_disabled( $post_id ) {
		return (bool) get_post_meta( $post_id, self::META_KEY, true );
	}
}
