<?php
/**
 * Configuration management.
 *
 * Handles advanced-cache.php dropin, WP_CACHE constant, and config file generation.
 */

defined( 'ABSPATH' ) || exit;

class Prime_Cache_Config {

	/**
	 * Generate and install the advanced-cache.php dropin.
	 *
	 * @return bool
	 */
	public static function install_advanced_cache() {
		$dropin_path = WP_CONTENT_DIR . '/advanced-cache.php';

		$content = self::get_advanced_cache_content();
		if ( false === $content ) {
			return false;
		}

		return (bool) file_put_contents( $dropin_path, $content ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	/**
	 * Remove the advanced-cache.php dropin.
	 *
	 * @return bool
	 */
	public static function uninstall_advanced_cache() {
		$dropin_path = WP_CONTENT_DIR . '/advanced-cache.php';

		if ( ! file_exists( $dropin_path ) ) {
			return true;
		}

		// Only remove if it's ours.
		$content = file_get_contents( $dropin_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( false !== strpos( $content, 'PRIME_CACHE' ) ) {
			return @unlink( $dropin_path );
		}

		return false;
	}

	/**
	 * Generate the advanced-cache.php content.
	 *
	 * @return string|false
	 */
	private static function get_advanced_cache_content() {
		$dropin_source = defined( 'PRIME_CACHE_DROPIN_SOURCE' )
			? PRIME_CACHE_DROPIN_SOURCE
			: WP_CONTENT_DIR . '/plugins/prime-cache/dropins/page-cache.php';

		$config_dir = defined( 'PRIME_CACHE_CONFIG_DIR' )
			? PRIME_CACHE_CONFIG_DIR
			: WP_CONTENT_DIR . '/prime-cache-config/';

		$cache_dir = defined( 'PRIME_CACHE_CACHE_DIR' )
			? PRIME_CACHE_CACHE_DIR
			: WP_CONTENT_DIR . '/cache/prime-cache/';

		return '<?php' . "\n"
			. '/** Generated by Prime Cache ' . PRIME_CACHE_VERSION . ' */' . "\n"
			. 'defined( \'ABSPATH\' ) || exit;' . "\n\n"
			. 'define( \'PRIME_CACHE_ADVANCED_CACHE\', true );' . "\n"
			. 'define( \'PRIME_CACHE_CACHE_DIR\', \'' . addslashes( $cache_dir ) . '\' );' . "\n"
			. 'define( \'PRIME_CACHE_CONFIG_DIR\', \'' . addslashes( $config_dir ) . '\' );' . "\n\n"
			. '$prime_cache_dropin = \'' . addslashes( $dropin_source ) . '\';' . "\n"
			. 'if ( is_readable( $prime_cache_dropin ) ) {' . "\n"
			. "\t" . 'include $prime_cache_dropin;' . "\n"
			. '}' . "\n";
	}

	/**
	 * Set WP_CACHE to true in wp-config.php.
	 *
	 * @return bool
	 */
	public static function set_wp_cache( $enable = true ) {
		$config_path = self::get_wp_config_path();
		if ( ! $config_path || ! is_writable( $config_path ) ) {
			return false;
		}

		$content = file_get_contents( $config_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( false === $content ) {
			return false;
		}

		// Remove existing WP_CACHE definition (exact constant name only, not WP_CACHE_KEY_SALT etc.).
		$content = preg_replace(
			'#^\s*define\s*\(\s*[\'"]WP_CACHE[\'"]\s*,\s*[^)]+\)\s*;\s*(?://[^\n]*)?\n?#mi',
			'',
			$content
		);

		if ( $enable ) {
			// Add WP_CACHE after opening PHP tag.
			$content = preg_replace(
				'#^<\?php\s*#',
				"<?php\ndefine( 'WP_CACHE', true ); // Added by Prime Cache\n",
				$content,
				1
			);
		}

		// Clean up double blank lines.
		$content = preg_replace( "#\n{3,}#", "\n\n", $content );

		return (bool) file_put_contents( $config_path, $content ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	/**
	 * Write the settings config file for the dropin to read.
	 *
	 * @param array $settings Plugin settings.
	 * @return bool
	 */
	public static function write_config_file( $settings ) {
		$config_dir = defined( 'PRIME_CACHE_CONFIG_DIR' )
			? PRIME_CACHE_CONFIG_DIR
			: WP_CONTENT_DIR . '/prime-cache-config/';

		if ( ! wp_mkdir_p( $config_dir ) ) {
			return false;
		}

		$host = wp_parse_url( home_url(), PHP_URL_HOST );
		$file = $config_dir . sanitize_file_name( $host ) . '.php';

		$lines   = array();
		$lines[] = '<?php';
		$lines[] = '/** Prime Cache config for ' . esc_html( $host ) . ' */';
		$lines[] = 'defined( \'ABSPATH\' ) || exit;';
		$lines[] = '';

		foreach ( $settings as $key => $value ) {
			// Validate key: only lowercase letters and underscores allowed.
			if ( ! preg_match( '#^[a-z_]+$#', $key ) ) {
				continue;
			}
			if ( is_bool( $value ) ) {
				$lines[] = '$prime_cache_config[\'' . $key . '\'] = ' . ( $value ? 'true' : 'false' ) . ';';
			} elseif ( is_int( $value ) ) {
				$lines[] = '$prime_cache_config[\'' . $key . '\'] = ' . (int) $value . ';';
			} else {
				$lines[] = '$prime_cache_config[\'' . $key . '\'] = \'' . addslashes( (string) $value ) . '\';';
			}
		}

		$lines[] = '';

		// Atomic write: temp file + rename.
		$content  = implode( "\n", $lines );
		$tempfile = $file . '.tmp.' . uniqid();
		if ( false === file_put_contents( $tempfile, $content ) ) { // phpcs:ignore
			return false;
		}
		if ( ! rename( $tempfile, $file ) ) { // phpcs:ignore
			@unlink( $tempfile );
			return false;
		}
		return true;
	}

	/**
	 * Delete the config file.
	 *
	 * @return bool
	 */
	public static function delete_config_file() {
		$config_dir = defined( 'PRIME_CACHE_CONFIG_DIR' )
			? PRIME_CACHE_CONFIG_DIR
			: WP_CONTENT_DIR . '/prime-cache-config/';

		$host = wp_parse_url( home_url(), PHP_URL_HOST );
		$file = $config_dir . sanitize_file_name( $host ) . '.php';

		if ( file_exists( $file ) ) {
			@unlink( $file );
		}

		// Remove config dir if empty.
		if ( is_dir( $config_dir ) ) {
			$remaining = glob( $config_dir . '*' );
			if ( empty( $remaining ) ) {
				@rmdir( $config_dir );
			}
		}

		return true;
	}

	/**
	 * Get available object cache backends.
	 *
	 * @return array Backend slug => display name, only if PHP extension is present.
	 */
	public static function get_available_object_caches() {
		$backends = array();

		if ( function_exists( 'apcu_add' ) ) {
			$backends['apcu'] = 'APCu';
		}

		if ( class_exists( 'Redis' ) ) {
			$backends['redis'] = 'Redis';
		}

		if ( class_exists( 'Memcached' ) ) {
			$backends['memcached'] = 'Memcached';
		}

		return $backends;
	}

	/**
	 * Get the dropin file path for a given backend.
	 *
	 * @param string $backend Backend slug.
	 * @return string|false
	 */
	public static function get_object_cache_dropin_path( $backend ) {
		$dropins = array(
			'apcu'      => PRIME_CACHE_PATH . 'dropins/apcu-object-cache.php',
			'redis'     => PRIME_CACHE_PATH . 'dropins/redis-object-cache.php',
			'memcached' => PRIME_CACHE_PATH . 'dropins/memcached-object-cache.php',
		);

		return isset( $dropins[ $backend ] ) ? $dropins[ $backend ] : false;
	}

	/**
	 * Install or remove the object-cache.php dropin.
	 *
	 * @param string $backend Backend slug ('off' to remove).
	 * @return bool
	 */
	public static function setup_object_cache( $backend = 'off' ) {
		$file = WP_CONTENT_DIR . '/object-cache.php';

		// Remove if turning off.
		if ( 'off' === $backend ) {
			if ( file_exists( $file ) ) {
				$content = file_get_contents( $file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
				if ( false !== strpos( $content, 'PRIME_OBJECT_CACHE' ) ) {
					@unlink( $file );
				}
			}
			return true;
		}

		$dropin_source = self::get_object_cache_dropin_path( $backend );
		if ( ! $dropin_source || ! is_readable( $dropin_source ) ) {
			return false;
		}

		// Refuse to overwrite another plugin's object-cache.php.
		if ( file_exists( $file ) ) {
			$existing = file_get_contents( $file ); // phpcs:ignore
			if ( false === strpos( $existing, 'PRIME_OBJECT_CACHE' ) ) {
				return false; // Not ours — do not overwrite.
			}
		}

		$content = self::get_object_cache_content( $backend, $dropin_source );

		return (bool) file_put_contents( $file, $content, LOCK_EX ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	/**
	 * Generate the object-cache.php dropin content.
	 *
	 * This dropin is loaded by WordPress before plugins. It sets up a cache key
	 * salt for multisite isolation, then loads the selected backend implementation.
	 *
	 * @param string $backend       Backend slug (apcu, redis, memcached).
	 * @param string $dropin_source Absolute path to the backend dropin file.
	 * @return string Generated PHP code.
	 */
	private static function get_object_cache_content( $backend, $dropin_source ) {
		$escaped_path = addslashes( $dropin_source );
		$version      = PRIME_CACHE_VERSION;
		$label        = ucfirst( $backend );

		return <<<PHP
<?php
/**
 * Object Cache dropin — {$label} backend.
 * Generated by Prime Cache {$version}. Do not edit manually.
 */
defined( 'ABSPATH' ) || exit;
define( 'PRIME_OBJECT_CACHE', true );

// Ensure cache keys are unique per database (important for multisite / shared hosting).
if ( ! defined( 'WP_CACHE_KEY_SALT' ) ) {
	define( 'WP_CACHE_KEY_SALT', defined( 'DB_NAME' ) ? DB_NAME . ':' : '' );
}

// Load the backend implementation.
\$backend_file = '{$escaped_path}';
if ( is_readable( \$backend_file ) ) {
	require_once \$backend_file;
}

PHP;
	}

	/**
	 * Get the currently active object cache backend.
	 *
	 * @return string Backend slug or 'off'.
	 */
	public static function get_active_object_cache() {
		$file = WP_CONTENT_DIR . '/object-cache.php';
		if ( ! file_exists( $file ) ) {
			return 'off';
		}

		$content = file_get_contents( $file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( false === strpos( $content, 'PRIME_OBJECT_CACHE' ) ) {
			return 'external';
		}

		if ( false !== strpos( $content, 'apcu-object-cache.php' ) ) {
			return 'apcu';
		}
		if ( false !== strpos( $content, 'redis-object-cache.php' ) ) {
			return 'redis';
		}
		if ( false !== strpos( $content, 'memcached-object-cache.php' ) ) {
			return 'memcached';
		}

		return 'off';
	}

	/**
	 * Find wp-config.php path.
	 *
	 * @return string|false
	 */
	private static function get_wp_config_path() {
		if ( file_exists( ABSPATH . 'wp-config.php' ) ) {
			return ABSPATH . 'wp-config.php';
		}

		if ( file_exists( dirname( ABSPATH ) . '/wp-config.php' ) ) {
			return dirname( ABSPATH ) . '/wp-config.php';
		}

		return false;
	}
}
