<?php
/**
 * Configuration management.
 *
 * Handles advanced-cache.php dropin, WP_CACHE constant, and config file generation.
 */

defined( 'ABSPATH' ) || exit;

class Prime_Cache_Config {

	/**
	 * Generate and install the advanced-cache.php dropin.
	 *
	 * Refuses to overwrite another plugin's advanced-cache.php.
	 *
	 * @return bool True on success, false if blocked or write failed.
	 */
	public static function install_advanced_cache() {
		$dropin_path = WP_CONTENT_DIR . '/advanced-cache.php';

		// Serialize the check-then-write sequence. Without a lock, two parallel
		// activations could both pass the ownership check against an external
		// dropin and then both rename their replacement on top of it. flock on
		// a sibling file (we cannot lock a file that does not exist yet, and
		// dropin_path itself may have an external owner we should not touch).
		$lock_path = WP_CONTENT_DIR . '/.prime-cache-acache.lock';
		$lock_fp   = @fopen( $lock_path, 'c' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fopen
		if ( $lock_fp ) {
			@flock( $lock_fp, LOCK_EX );
		}

		try {
			if ( file_exists( $dropin_path ) ) {
				$existing = file_get_contents( $dropin_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents

				// Unreadable file (permissions / FS error). Refuse to overwrite — assume
				// it is an external dropin we cannot inspect, rather than risk clobbering it.
				if ( false === $existing ) {
					return false;
				}

				// Recognize Prime Cache dropins (new signature, legacy constant, legacy comment).
				$is_ours = false !== strpos( $existing, 'PRIME_CACHE_DROPIN_SIGNATURE' )
					|| false !== strpos( $existing, 'PRIME_CACHE_ADVANCED_CACHE' )
					|| false !== strpos( $existing, 'Generated by Prime Cache' );

				// Treat empty or near-empty files as abandoned remnants.
				$is_abandoned = strlen( trim( $existing ) ) < 20;

				// Detect dropins left behind by deactivated plugins.
				// WP Rocket, W3 Total Cache, WP Super Cache etc. leave their
				// advanced-cache.php when deactivated. If the owning plugin is
				// no longer active, the dropin is orphaned and safe to replace.
				if ( ! $is_ours && ! $is_abandoned ) {
					$is_orphaned = self::is_orphaned_dropin( $existing );
					if ( ! $is_orphaned ) {
						return false; // Active external dropin — do not overwrite.
					}
				}
			}

			$content = self::get_advanced_cache_content();
			if ( false === $content ) {
				return false;
			}

			// Skip the write when the existing dropin already matches byte-for-byte.
			// get_advanced_cache_content() is deterministic (no timestamps), so this
			// makes the common admin_init self-heal pass a true no-op.
			if ( isset( $existing ) && $existing === $content ) {
				return true;
			}

			// Atomic write: temp file + rename.
			$tempfile = $dropin_path . '.tmp.' . getmypid();
			if ( false === file_put_contents( $tempfile, $content ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
				return false;
			}
			if ( ! rename( $tempfile, $dropin_path ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename
				@unlink( $tempfile );
				return false;
			}
			return true;
		} finally {
			if ( $lock_fp ) {
				@flock( $lock_fp, LOCK_UN );
				@fclose( $lock_fp );
			}
		}
	}

	/**
	 * Check if an advanced-cache.php dropin belongs to a deactivated plugin.
	 *
	 * Known cache plugins that leave their dropin after deactivation:
	 * WP Rocket, W3 Total Cache, WP Super Cache, LiteSpeed Cache, etc.
	 *
	 * @param string $content Dropin file contents.
	 * @return bool True if the owning plugin is not active.
	 */
	private static function is_orphaned_dropin( $content ) {
		// Map: signature in advanced-cache.php → plugin file to check.
		$signatures = array(
			'WP_ROCKET_ADVANCED_CACHE'       => 'wp-rocket/wp-rocket.php',
			'WP Rocket'                      => 'wp-rocket/wp-rocket.php',
			'W3TC_POWERED_BY'                => 'w3-total-cache/w3-total-cache.php',
			'W3 Total Cache'                 => 'w3-total-cache/w3-total-cache.php',
			'WPCACHEHOME'                    => 'wp-super-cache/wp-cache.php',
			'WP Super Cache'                 => 'wp-super-cache/wp-cache.php',
			'LSCWP_V'                        => 'litespeed-cache/litespeed-cache.php',
			'LiteSpeed'                      => 'litespeed-cache/litespeed-cache.php',
			'POWERED_CACHE_PATH'             => 'powered-cache/powered-cache.php',
			'Powered Cache'                  => 'powered-cache/powered-cache.php',
			'BREEZE_PLUGIN_DIR'              => 'breeze/breeze.php',
			'WP_FASTEST_CACHE'               => 'wp-fastest-cache/wpFastestCache.php',
			'STARTER_CACHE_ADVANCED_CACHE'   => 'starter-cache/starter-cache.php',
		);

		if ( ! function_exists( 'is_plugin_active' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}

		foreach ( $signatures as $signature => $plugin_file ) {
			if ( false !== strpos( $content, $signature ) ) {
				// Found signature — check if that plugin is still active.
				return ! is_plugin_active( $plugin_file );
			}
		}

		// Fail-safe: an unrecognized dropin may belong to a custom caching layer or
		// a niche plugin not in our signatures table. Refuse to overwrite — wrongly
		// clobbering a working dropin breaks the site, while declining to overwrite
		// just means Prime Cache's page cache stays disabled (the admin gets an
		// "external dropin detected" warning and can manually replace it).
		return false;
	}

	/**
	 * Check if the current advanced-cache.php belongs to Prime Cache.
	 *
	 * @return string 'ours', 'external', 'orphaned', 'abandoned', or 'none'.
	 */
	public static function get_advanced_cache_owner() {
		$dropin_path = WP_CONTENT_DIR . '/advanced-cache.php';
		if ( ! file_exists( $dropin_path ) ) {
			return 'none';
		}
		$content = file_get_contents( $dropin_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		// Unreadable: report 'external' so install_advanced_cache() also refuses to overwrite.
		if ( false === $content ) {
			return 'external';
		}
		if ( false !== strpos( $content, 'PRIME_CACHE_DROPIN_SIGNATURE' )
			|| false !== strpos( $content, 'PRIME_CACHE_ADVANCED_CACHE' )
			|| false !== strpos( $content, 'Generated by Prime Cache' ) ) {
			return 'ours';
		}
		// Empty or near-empty files are leftover remnants, not active dropins.
		if ( strlen( trim( $content ) ) < 20 ) {
			return 'abandoned';
		}
		// Check if the owning plugin is deactivated.
		if ( self::is_orphaned_dropin( $content ) ) {
			return 'orphaned';
		}
		return 'external';
	}

	/**
	 * Remove the advanced-cache.php dropin.
	 *
	 * @return bool
	 */
	public static function uninstall_advanced_cache() {
		$dropin_path = WP_CONTENT_DIR . '/advanced-cache.php';

		if ( ! file_exists( $dropin_path ) ) {
			return true;
		}

		// Only remove if it's ours (recognize both new and legacy signatures).
		$content = file_get_contents( $dropin_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( false === $content ) {
			return false; // Unreadable — refuse to delete an unidentified dropin.
		}
		if ( false !== strpos( $content, 'PRIME_CACHE_DROPIN_SIGNATURE' )
			|| false !== strpos( $content, 'PRIME_CACHE_ADVANCED_CACHE' )
			|| false !== strpos( $content, 'Generated by Prime Cache' ) ) {
			return @unlink( $dropin_path );
		}

		return false;
	}

	/**
	 * Generate the advanced-cache.php content.
	 *
	 * @return string|false
	 */
	private static function get_advanced_cache_content() {
		$dropin_source = defined( 'PRIME_CACHE_DROPIN_SOURCE' )
			? PRIME_CACHE_DROPIN_SOURCE
			: WP_CONTENT_DIR . '/plugins/prime-cache/dropins/page-cache.php';

		$config_dir = defined( 'PRIME_CACHE_CONFIG_DIR' )
			? PRIME_CACHE_CONFIG_DIR
			: WP_CONTENT_DIR . '/prime-cache-config/';

		$cache_dir = defined( 'PRIME_CACHE_CACHE_DIR' )
			? PRIME_CACHE_CACHE_DIR
			: WP_CONTENT_DIR . '/cache/prime-cache/';

		return '<?php' . "\n"
			. '// PRIME_CACHE_DROPIN_SIGNATURE — do not remove this marker.' . "\n"
			. '/** Generated by Prime Cache ' . PRIME_CACHE_VERSION . ' */' . "\n"
			. 'defined( \'ABSPATH\' ) || exit;' . "\n\n"
			. 'define( \'PRIME_CACHE_ADVANCED_CACHE\', true );' . "\n"
			. 'define( \'PRIME_CACHE_CACHE_DIR\', \'' . addslashes( $cache_dir ) . '\' );' . "\n"
			. 'define( \'PRIME_CACHE_CONFIG_DIR\', \'' . addslashes( $config_dir ) . '\' );' . "\n\n"
			. '$prime_cache_dropin = \'' . addslashes( $dropin_source ) . '\';' . "\n"
			. 'if ( is_readable( $prime_cache_dropin ) ) {' . "\n"
			. "\t" . 'include $prime_cache_dropin;' . "\n"
			. '}' . "\n";
	}

	/**
	 * Set WP_CACHE to true in wp-config.php.
	 *
	 * @return bool
	 */
	public static function set_wp_cache( $enable = true ) {
		$config_path = self::get_wp_config_path();
		if ( ! $config_path || ! is_writable( $config_path ) ) {
			return false;
		}

		$content = file_get_contents( $config_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( false === $content ) {
			return false;
		}
		$original_content = $content;

		$prime_cache_marker = '// Added by Prime Cache';
		$has_prime_line     = false !== strpos( $content, $prime_cache_marker );

		// Only remove WP_CACHE lines that Prime Cache added (identified by comment marker).
		if ( $has_prime_line ) {
			$content = preg_replace(
				'#^\s*define\s*\(\s*[\'"]WP_CACHE[\'"]\s*,\s*[^)]+\)\s*;\s*//\s*Added by Prime Cache[^\n]*\n?#mi',
				'',
				$content
			);
		}

		if ( $enable ) {
			// Check if a WP_CACHE definition already exists (from another source).
			if ( preg_match( '#^\s*define\s*\(\s*[\'"]WP_CACHE[\'"]\s*,\s*(?:false|0|null)\s*\)#mi', $content ) ) {
				// Another plugin left WP_CACHE as false — replace with true.
				$content = preg_replace(
					'#^(\s*define\s*\(\s*[\'"]WP_CACHE[\'"]\s*,\s*)(?:false|0|null)(\s*\).*)$#mi',
					'${1}true${2} ' . $prime_cache_marker,
					$content
				);
			} elseif ( ! preg_match( '#^\s*define\s*\(\s*[\'"]WP_CACHE[\'"]\s*,#mi', $content ) ) {
				// No WP_CACHE definition exists — add after opening PHP tag.
				// Track the replacement count so we can detect a missed insertion
				// (BOM/whitespace/comment before <?php) and fail loudly instead
				// of returning a misleading success via the unchanged-content
				// short-circuit below.
				$replacements = 0;
				$content = preg_replace(
					'#^<\?php\s*#',
					"<?php\ndefine( 'WP_CACHE', true ); " . $prime_cache_marker . "\n",
					$content,
					1,
					$replacements
				);
				if ( null === $content || 1 !== $replacements ) {
					return false;
				}
			}
			// Otherwise WP_CACHE is already true (possibly set by another caching
			// plugin) — leave the existing line untouched to avoid ownership churn.
		}

		// Clean up double blank lines.
		$content = preg_replace( "#\n{3,}#", "\n\n", $content );

		// Skip the rewrite when nothing actually changed. The self-heal pass on
		// admin_init calls this on every admin page load — if the file already
		// reflects the desired state, leave its mtime alone to avoid noise for
		// backup tools and file watchers.
		if ( $original_content === $content ) {
			return true;
		}

		// Atomic write: temp file + rename.
		$tempfile = $config_path . '.tmp.' . getmypid();
		if ( false === file_put_contents( $tempfile, $content ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
			return false;
		}
		if ( ! rename( $tempfile, $config_path ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename
			@unlink( $tempfile );
			return false;
		}
		return true;
	}

	/**
	 * Write the settings config file for the dropin to read.
	 *
	 * @param array $settings Plugin settings.
	 * @return bool
	 */
	public static function write_config_file( $settings ) {
		$config_dir = defined( 'PRIME_CACHE_CONFIG_DIR' )
			? PRIME_CACHE_CONFIG_DIR
			: WP_CONTENT_DIR . '/prime-cache-config/';

		if ( ! wp_mkdir_p( $config_dir ) ) {
			return false;
		}

		// Install-unique config file. Uses ABSPATH + DB_NAME + table_prefix
		// so installs that share a wp-content and DB but differ in either
		// filesystem path or table prefix (WordPress multi-install pattern)
		// get distinct filenames. AUTH_SALT was previously folded in for
		// extra isolation but `wp salt rotate` would then orphan the
		// existing config file — the drop-in fails closed until the next
		// admin page load — so it is deliberately excluded. $table_prefix
		// is set globally by wp-config.php before either WP or the drop-in
		// reads it, and is stable across salt rotation.
		global $table_prefix;
		$install_seed = ABSPATH . '|' . DB_NAME . '|' . ( isset( $table_prefix ) ? $table_prefix : '' );
		$install_key  = substr( md5( $install_seed ), 0, 8 );
		$file = $config_dir . 'site-config-' . $install_key . '.php';

		// Serialize concurrent writes (settings save / schema migration / preset
		// apply / self-heal can all land in the same instant). Without a lock,
		// a stale snapshot from one path can overwrite a fresher write.
		$lock_path = $config_dir . '.prime-cache-config.lock';
		$lock_fp   = @fopen( $lock_path, 'c' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fopen
		if ( $lock_fp ) {
			@flock( $lock_fp, LOCK_EX );
		}

		try {
			$lines   = array();
			$lines[] = '<?php';
			$lines[] = '/** Prime Cache site config — generated ' . gmdate( 'Y-m-d H:i:s' ) . ' UTC */';

			$lines[] = 'defined( \'ABSPATH\' ) || exit;';
			$lines[] = '';

			foreach ( $settings as $key => $value ) {
				// Validate key: lowercase letters, digits, and underscores allowed.
				if ( ! preg_match( '#^[a-z0-9_]+$#', $key ) ) {
					continue;
				}
				if ( is_bool( $value ) ) {
					$lines[] = '$prime_cache_config[\'' . $key . '\'] = ' . ( $value ? 'true' : 'false' ) . ';';
				} elseif ( is_int( $value ) ) {
					$lines[] = '$prime_cache_config[\'' . $key . '\'] = ' . (int) $value . ';';
				} else {
					$lines[] = '$prime_cache_config[\'' . $key . '\'] = \'' . addslashes( (string) $value ) . '\';';
				}
			}

			// Allowed hosts: dropin compares the request Host against this list to prevent
			// arbitrary-Host requests from creating cache buckets (disk-fill DoS).
			// Operators serving the same site under additional alias domains
			// (www↔apex, language subdomains, alternate CCTLDs) extend this
			// list via the `prime_cache_allowed_hosts` filter — without it,
			// requests on the aliases would be rejected by the drop-in and
			// never cached.
			require_once PRIME_CACHE_PATH . 'includes/cache-key-functions.php';
			$allowed_hosts = array();
			foreach ( array( home_url(), site_url() ) as $u ) {
				$h = wp_parse_url( $u, PHP_URL_HOST );
				if ( $h ) {
					$allowed_hosts[] = _prime_cache_normalize_host( $h );
				}
			}
			/**
			 * Filter the list of hostnames Prime Cache will cache for.
			 *
			 * @param string[] $allowed_hosts Normalized hostnames (lowercase, IDN→Punycode).
			 */
			$allowed_hosts = apply_filters( 'prime_cache_allowed_hosts', $allowed_hosts );
			if ( ! is_array( $allowed_hosts ) ) {
				$allowed_hosts = array();
			}
			// Re-normalize anything the filter may have added in raw form,
			// then prune empties/dupes.
			$allowed_hosts = array_map(
				function ( $h ) {
					return is_string( $h ) ? _prime_cache_normalize_host( $h ) : '';
				},
				$allowed_hosts
			);
			$allowed_hosts = array_values( array_unique( array_filter( $allowed_hosts ) ) );
			$host_literals = array();
			foreach ( $allowed_hosts as $h ) {
				// Normalized hosts contain only [a-z0-9.\-_], so addslashes is a belt-and-braces guard.
				$host_literals[] = "'" . addslashes( $h ) . "'";
			}
			$lines[] = '$prime_cache_allowed_hosts = array(' . implode( ', ', $host_literals ) . ');';

			// Site scheme: derived from home_url(). The dropin trusts this over spoofable
			// $_SERVER['HTTPS']/X-Forwarded-Proto headers, which auto-handles reverse proxies.
			// Only sites that intentionally mix http://+https:// (cache_mixed_scheme=true) fall
			// back to per-request header detection.
			$site_scheme = wp_parse_url( home_url(), PHP_URL_SCHEME );
			if ( 'http' !== $site_scheme && 'https' !== $site_scheme ) {
				$site_scheme = ''; // Unknown — dropin will fall through to header detection.
			}
			$lines[] = '$prime_cache_site_scheme = \'' . $site_scheme . '\';';

			$lines[] = '';

			$content = implode( "\n", $lines );

			// Skip the write entirely when the resulting config matches the existing
			// file. The timestamp comment changes every call, so strip just that line
			// from both sides and byte-compare the rest. Comparing the full body
			// (rather than extracted data lines) is necessary because textarea values
			// can contain literal newlines — addslashes() does not escape them.
			if ( file_exists( $file ) ) {
				$existing = @file_get_contents( $file ); // phpcs:ignore
				if ( false !== $existing ) {
					$strip            = '#^/\*\* Prime Cache site config[^\n]*\*/\n?#m';
					$new_normalized   = preg_replace( $strip, '', $content );
					$exist_normalized = preg_replace( $strip, '', $existing );
					if ( $new_normalized === $exist_normalized ) {
						return true;
					}
				}
			}

			// Atomic write: temp file + rename.
			$tempfile = $file . '.tmp.' . uniqid();
			if ( false === file_put_contents( $tempfile, $content ) ) { // phpcs:ignore
				return false;
			}
			if ( ! rename( $tempfile, $file ) ) { // phpcs:ignore
				@unlink( $tempfile );
				return false;
			}
			return true;
		} finally {
			if ( $lock_fp ) {
				@flock( $lock_fp, LOCK_UN );
				@fclose( $lock_fp );
			}
		}
	}

	/**
	 * Delete the config file.
	 *
	 * @return bool
	 */
	public static function delete_config_file() {
		$config_dir = defined( 'PRIME_CACHE_CONFIG_DIR' )
			? PRIME_CACHE_CONFIG_DIR
			: WP_CONTENT_DIR . '/prime-cache-config/';

		// Match the install_seed formula used by write_config_file() — if
		// these diverge, deactivation silently leaks the actual config file
		// while only the old hash gets cleaned up.
		global $table_prefix;
		$install_seed = ABSPATH . '|' . DB_NAME . '|' . ( isset( $table_prefix ) ? $table_prefix : '' );
		$install_key  = substr( md5( $install_seed ), 0, 8 );
		$file = $config_dir . 'site-config-' . $install_key . '.php';

		if ( file_exists( $file ) ) {
			@unlink( $file );
		}

		// Also remove the previous-format file if a pre-upgrade build of this
		// install wrote one with the AUTH_SALT-derived key. Without this, a
		// rotate-then-deactivate path can leave the older file behind.
		$legacy_seed = ABSPATH . '|' . DB_NAME . '|' . ( defined( 'AUTH_SALT' ) ? AUTH_SALT : '' );
		$legacy_key  = substr( md5( $legacy_seed ), 0, 8 );
		if ( $legacy_key !== $install_key ) {
			$legacy_file = $config_dir . 'site-config-' . $legacy_key . '.php';
			if ( file_exists( $legacy_file ) ) {
				@unlink( $legacy_file );
			}
		}

		// Only clean up the legacy fixed-name config (pre-install-key era).
		// Do NOT glob-delete site-config-*.php — other installs sharing this
		// wp-content directory have their own install-key-based config files.
		$legacy_plain = $config_dir . 'site-config.php';
		if ( file_exists( $legacy_plain ) ) {
			@unlink( $legacy_plain );
		}

		// Remove the per-config-dir flock sentinel write_config_file() leaves
		// behind. glob('*') hides dotfiles, so without this rmdir would fail
		// on every deactivation that ever called write_config_file().
		@unlink( $config_dir . '.prime-cache-config.lock' );

		// Remove config dir if empty. Use scandir so dotfiles (lockfile,
		// hidden temp) are visible — glob('*') alone would silently miss
		// them and the rmdir below would fail every time.
		if ( is_dir( $config_dir ) ) {
			$entries = @scandir( $config_dir );
			if ( false !== $entries ) {
				$entries = array_diff( $entries, array( '.', '..' ) );
				if ( empty( $entries ) ) {
					@rmdir( $config_dir );
				}
			}
		}

		return true;
	}

	/**
	 * Get available object cache backends.
	 *
	 * @return array Backend slug => display name, only if PHP extension is present.
	 */
	public static function get_available_object_caches() {
		$backends = array();

		if ( function_exists( 'apcu_add' ) ) {
			$backends['apcu'] = 'APCu';
		}

		if ( class_exists( 'Redis' ) ) {
			$backends['redis'] = 'Redis';
		}

		if ( class_exists( 'Memcached' ) ) {
			$backends['memcached'] = 'Memcached';
		}

		return $backends;
	}

	/**
	 * Get the dropin file path for a given backend.
	 *
	 * @param string $backend Backend slug.
	 * @return string|false
	 */
	public static function get_object_cache_dropin_path( $backend ) {
		// Object cache dropins are in Pro add-on.
		$pro_path = defined( 'PRIME_CACHE_PRO_PATH' ) ? PRIME_CACHE_PRO_PATH : PRIME_CACHE_PATH;
		$dropins = array(
			'apcu'      => $pro_path . 'dropins/apcu-object-cache.php',
			'redis'     => $pro_path . 'dropins/redis-object-cache.php',
			'memcached' => $pro_path . 'dropins/memcached-object-cache.php',
		);

		return isset( $dropins[ $backend ] ) ? $dropins[ $backend ] : false;
	}

	/**
	 * Install or remove the object-cache.php dropin.
	 *
	 * @param string $backend Backend slug ('off' to remove).
	 * @return bool
	 */
	public static function setup_object_cache( $backend = 'off' ) {
		$file = WP_CONTENT_DIR . '/object-cache.php';

		// Remove if turning off.
		if ( 'off' === $backend ) {
			if ( file_exists( $file ) ) {
				$content = file_get_contents( $file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
				if ( false === $content ) {
					return false; // Unreadable — refuse to delete an unidentified dropin.
				}
				if ( false !== strpos( $content, 'PRIME_CACHE_DROPIN_SIGNATURE' ) ) {
					// Surface unlink failure (permissions, opcache holding the
					// file) so callers don't render a misleading "Disabled"
					// notice while the dropin is still on disk and active.
					return (bool) @unlink( $file );
				}
				// External drop-in exists — cannot disable, report failure.
				return false;
			}
			return true;
		}

		$dropin_source = self::get_object_cache_dropin_path( $backend );
		if ( ! $dropin_source || ! is_readable( $dropin_source ) ) {
			return false;
		}

		// Refuse to overwrite another plugin's object-cache.php.
		if ( file_exists( $file ) ) {
			$existing = file_get_contents( $file ); // phpcs:ignore
			// Unreadable or not ours — do not overwrite.
			if ( false === $existing || false === strpos( $existing, 'PRIME_CACHE_DROPIN_SIGNATURE' ) ) {
				return false;
			}
		}

		$content = self::get_object_cache_content( $backend, $dropin_source );

		// Atomic write: temp file + rename.
		$tempfile = $file . '.tmp.' . getmypid();
		if ( false === file_put_contents( $tempfile, $content ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
			return false;
		}
		if ( ! rename( $tempfile, $file ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename
			@unlink( $tempfile );
			return false;
		}
		return true;
	}

	/**
	 * Generate the object-cache.php dropin content.
	 *
	 * This dropin is loaded by WordPress before plugins. It sets up a cache key
	 * salt for multisite isolation, then loads the selected backend implementation.
	 *
	 * @param string $backend       Backend slug (apcu, redis, memcached).
	 * @param string $dropin_source Absolute path to the backend dropin file.
	 * @return string Generated PHP code.
	 */
	private static function get_object_cache_content( $backend, $dropin_source ) {
		$escaped_path = addslashes( $dropin_source );
		$version      = PRIME_CACHE_VERSION;
		$label        = ucfirst( $backend );

		return <<<PHP
<?php
// PRIME_CACHE_DROPIN_SIGNATURE — do not remove this marker.
/**
 * Object Cache dropin — {$label} backend.
 * Generated by Prime Cache {$version}. Do not edit manually.
 */
defined( 'ABSPATH' ) || exit;
define( 'PRIME_OBJECT_CACHE', true );

// Ensure cache keys are unique per WordPress install. DB_NAME alone collides
// when two installs share a database via different table_prefix; mixing in an
// ABSPATH+AUTH_SALT hash makes the salt install-unique without depending on
// runtime state (\$table_prefix is not set at object-cache.php load time).
if ( ! defined( 'WP_CACHE_KEY_SALT' ) ) {
	\$pc_salt_seed = ( defined( 'DB_NAME' ) ? DB_NAME : '' )
		. '|' . ABSPATH
		. '|' . ( defined( 'AUTH_SALT' ) ? AUTH_SALT : '' );
	define( 'WP_CACHE_KEY_SALT', ( defined( 'DB_NAME' ) ? DB_NAME : '' ) . ':' . substr( md5( \$pc_salt_seed ), 0, 8 ) . ':' );
	unset( \$pc_salt_seed );
}

// Load the backend implementation.
\$backend_file = '{$escaped_path}';
if ( is_readable( \$backend_file ) ) {
	require_once \$backend_file;
}

PHP;
	}

	/**
	 * Get the currently active object cache backend.
	 *
	 * @return string Backend slug or 'off'.
	 */
	public static function get_active_object_cache() {
		$file = WP_CONTENT_DIR . '/object-cache.php';
		if ( ! file_exists( $file ) ) {
			return 'off';
		}

		$content = file_get_contents( $file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		// Unreadable: report 'external' so callers don't assume it's ours.
		if ( false === $content || false === strpos( $content, 'PRIME_CACHE_DROPIN_SIGNATURE' ) ) {
			return 'external';
		}

		// Determine which backend the dropin references, then verify the backend
		// file is actually readable. The dropin no-ops at runtime when the
		// backend file is missing (`if ( is_readable( $backend_file ) )`), so
		// reporting the slug alone would make the UI/CLI claim caching is on
		// while no caching is happening. Return 'broken' so callers can surface
		// the mismatch instead of silently lying.
		$backend = '';
		if ( false !== strpos( $content, 'apcu-object-cache.php' ) ) {
			$backend = 'apcu';
		} elseif ( false !== strpos( $content, 'redis-object-cache.php' ) ) {
			$backend = 'redis';
		} elseif ( false !== strpos( $content, 'memcached-object-cache.php' ) ) {
			$backend = 'memcached';
		}

		if ( '' === $backend ) {
			return 'off';
		}

		$backend_path = self::get_object_cache_dropin_path( $backend );
		if ( ! $backend_path || ! is_readable( $backend_path ) ) {
			return 'broken';
		}

		return $backend;
	}

	/**
	 * Find wp-config.php path.
	 *
	 * @return string|false
	 */
	private static function get_wp_config_path() {
		if ( file_exists( ABSPATH . 'wp-config.php' ) ) {
			return ABSPATH . 'wp-config.php';
		}

		if ( file_exists( dirname( ABSPATH ) . '/wp-config.php' ) ) {
			return dirname( ABSPATH ) . '/wp-config.php';
		}

		return false;
	}

	/**
	 * Verify that WP_CACHE is set to true in wp-config.php by reading the file.
	 *
	 * This is necessary because PHP constants loaded at the start of the request
	 * do not reflect changes made by set_wp_cache() during the same request.
	 *
	 * @return bool True if wp-config.php contains WP_CACHE set to true.
	 */
	public static function verify_wp_cache_enabled() {
		$config_path = self::get_wp_config_path();
		if ( ! $config_path ) {
			return false;
		}

		$content = file_get_contents( $config_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( false === $content ) {
			return false;
		}

		// Use PHP's tokenizer for accurate parsing — avoids false matches
		// inside strings, comments, or malformed code.
		$tokens = token_get_all( $content );
		$count  = count( $tokens );

		for ( $i = 0; $i < $count; $i++ ) {
			// Look for: define ( 'WP_CACHE' , <value> )
			if ( ! is_array( $tokens[ $i ] ) || T_STRING !== $tokens[ $i ][0] || 'define' !== strtolower( $tokens[ $i ][1] ) ) {
				continue;
			}

			// Scan forward for ( 'WP_CACHE' , <value> ).
			$j = $i + 1;
			// Skip whitespace.
			while ( $j < $count && is_array( $tokens[ $j ] ) && T_WHITESPACE === $tokens[ $j ][0] ) { $j++; }
			// Expect (
			if ( $j >= $count || '(' !== $tokens[ $j ] ) { continue; }
			$j++;
			while ( $j < $count && is_array( $tokens[ $j ] ) && T_WHITESPACE === $tokens[ $j ][0] ) { $j++; }
			// Expect string constant 'WP_CACHE' or "WP_CACHE".
			if ( $j >= $count || ! is_array( $tokens[ $j ] ) || T_CONSTANT_ENCAPSED_STRING !== $tokens[ $j ][0] ) { continue; }
			$const_name = trim( $tokens[ $j ][1], "\"'" );
			if ( 'WP_CACHE' !== $const_name ) { continue; }
			$j++;
			while ( $j < $count && is_array( $tokens[ $j ] ) && T_WHITESPACE === $tokens[ $j ][0] ) { $j++; }
			// Expect comma.
			if ( $j >= $count || ',' !== $tokens[ $j ] ) { continue; }
			$j++;
			while ( $j < $count && is_array( $tokens[ $j ] ) && T_WHITESPACE === $tokens[ $j ][0] ) { $j++; }
			// Read the value token.
			if ( $j >= $count ) { continue; }

			if ( is_array( $tokens[ $j ] ) ) {
				$val = strtolower( $tokens[ $j ][1] );
				// PHP uses first define() — return immediately.
				return in_array( $val, array( 'true', '1' ), true );
			}

			// Non-array token (e.g. a number literal).
			return '1' === $tokens[ $j ];
		}

		return false; // No WP_CACHE definition found.
	}
}
